apiVersion: v1
kind: Pod
metadata:
  name: root-pod
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        runAsUser: 0
        runAsNonRoot: false