apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredRunAsNonRoot
metadata:
  name: required-run-as-non-root
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "audit-zone"
  parameters: {}