apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: disallowedhostpaths
spec:
  crd:
    spec:
      names:
        kind: DisallowedHostPaths
      validation:
        openAPIV3Schema:
          type: object
          properties:
            forbiddenPaths:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package disallowedhostpaths

        violation[{"msg": msg}] {
          volume := input.review.object.spec.volumes[_]
          volume.hostPath
          msg := sprintf("HostPath volume %v is not allowed in pod %v", [volume.name, input.review.object.metadata.name])
        }