apiVersion: v1
kind: Pod
metadata:
  name: secure-privileged-pod
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1001