apiVersion: v1
kind: Pod
metadata:
  name: secure-hostpath-pod
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: temp-volume
          mountPath: /tmp
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        readOnlyRootFilesystem: false
  volumes:
    - name: temp-volume
      emptyDir: {}