apiVersion: v1
kind: Pod
metadata:
  name: secure-root-pod
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        readOnlyRootFilesystem: true